import type {
  User,
  Movie,
  Show,
  MovieRating,
  ShowRating,
  FeedActivity,
  CommunityItem,
  WatchlistItem,
  Comment,
  Notification,
  NowPlayingMovie,
  UpcomingMovie,
  NewShowEntry,
  NowStreamingEntry,
  NowWatching,
} from "./types";
export const currentUser: User = {
  id: "u1",
  name: "Gavin Ostrow",
  username: "gavin",
  bio: "Movies are better with commentary you'll never share.",
  favoriteGenres: ["Sci-Fi", "Drama", "Thriller"],
};
export const friends: User[] = [
  {
    id: "u2",
    name: "Emma Chen",
    username: "emma_c",
    favoriteGenres: ["Drama", "Horror", "Romance"],
  },
  {
    id: "u3",
    name: "Marcus Williams",
    username: "marcusw",
    favoriteGenres: ["Sci-Fi", "Action", "Crime"],
  },
  {
    id: "u4",
    name: "Sofia Rodriguez",
    username: "sofia_r",
    favoriteGenres: ["Drama", "Comedy", "Musical"],
  },
  {
    id: "u5",
    name: "Jake Park",
    username: "jake_p",
    favoriteGenres: ["Horror", "Thriller", "Mystery"],
  },
];
export const movies: Movie[] = [
  {
    id: "m1",
    tmdbId: 27205,
    posterPath: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    title: "Inception",
    year: 2010,
    genre: ["Sci-Fi", "Thriller", "Action"],
    director: "Christopher Nolan",
    runtime: 148,
    description:
      "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into a target's mind.",
    cast: [
      "Leonardo DiCaprio",
      "Joseph Gordon-Levitt",
      "Elliot Page",
      "Tom Hardy",
      "Cillian Murphy",
      "Ken Watanabe",
    ],
  },
  {
    id: "m2",
    tmdbId: 155,
    posterPath: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    title: "The Dark Knight",
    year: 2008,
    genre: ["Action", "Drama", "Thriller"],
    director: "Christopher Nolan",
    runtime: 152,
    description:
      "Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy and forces the hero to question everything he believes.",
    cast: [
      "Christian Bale",
      "Heath Ledger",
      "Aaron Eckhart",
      "Michael Caine",
      "Maggie Gyllenhaal",
      "Gary Oldman",
    ],
  },
  {
    id: "m3",
    tmdbId: 157336,
    posterPath: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    title: "Interstellar",
    year: 2014,
    genre: ["Sci-Fi", "Drama", "Adventure"],
    director: "Christopher Nolan",
    runtime: 169,
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    cast: [
      "Matthew McConaughey",
      "Anne Hathaway",
      "Jessica Chastain",
      "Michael Caine",
      "Matt Damon",
    ],
  },
  {
    id: "m4",
    tmdbId: 496243,
    posterPath: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    title: "Parasite",
    year: 2019,
    genre: ["Drama", "Thriller", "Comedy"],
    director: "Bong Joon-ho",
    runtime: 132,
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    cast: [
      "Song Kang-ho",
      "Lee Sun-kyun",
      "Cho Yeo-jeong",
      "Choi Woo-shik",
      "Park So-dam",
    ],
  },
  {
    id: "m5",
    tmdbId: 872585,
    posterPath: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    title: "Oppenheimer",
    year: 2023,
    genre: ["Drama", "History", "Thriller"],
    director: "Christopher Nolan",
    runtime: 180,
    description:
      "The story of J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    cast: [
      "Cillian Murphy",
      "Emily Blunt",
      "Matt Damon",
      "Robert Downey Jr.",
      "Florence Pugh",
      "Josh Hartnett",
    ],
  },
  {
    id: "m6",
    tmdbId: 545611,
    posterPath: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    title: "Everything Everywhere All at Once",
    year: 2022,
    genre: ["Sci-Fi", "Comedy", "Drama"],
    director: "The Daniels",
    runtime: 139,
    description:
      "An aging Chinese immigrant is swept up in an insane adventure where she must connect with parallel universe versions of herself to save the world.",
    cast: [
      "Michelle Yeoh",
      "Ke Huy Quan",
      "Jamie Lee Curtis",
      "Stephanie Hsu",
      "James Hong",
    ],
  },
  {
    id: "m7",
    tmdbId: 438631,
    posterPath: "/d5NXSklpcvkCiteMHkijOptiFaz.jpg",
    title: "Dune: Part One",
    year: 2021,
    genre: ["Sci-Fi", "Adventure", "Drama"],
    director: "Denis Villeneuve",
    runtime: 155,
    description:
      "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset on a desert planet.",
    cast: [
      "Timothée Chalamet",
      "Rebecca Ferguson",
      "Oscar Isaac",
      "Josh Brolin",
      "Zendaya",
      "Jason Momoa",
    ],
  },
  {
    id: "m8",
    tmdbId: 693134,
    posterPath: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    title: "Dune: Part Two",
    year: 2024,
    genre: ["Sci-Fi", "Adventure", "Drama"],
    director: "Denis Villeneuve",
    runtime: 166,
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    cast: [
      "Timothée Chalamet",
      "Zendaya",
      "Rebecca Ferguson",
      "Austin Butler",
      "Florence Pugh",
      "Christopher Walken",
    ],
  },
  {
    id: "m9",
    tmdbId: 419430,
    posterPath: "/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    title: "Get Out",
    year: 2017,
    genre: ["Horror", "Thriller", "Mystery"],
    director: "Jordan Peele",
    runtime: 104,
    description:
      "A young African-American man visits his white girlfriend's family and discovers something terrifyingly sinister beneath the surface.",
    cast: [
      "Daniel Kaluuya",
      "Allison Williams",
      "Bradley Whitford",
      "Catherine Keener",
      "Caleb Landry Jones",
    ],
  },
  {
    id: "m10",
    tmdbId: 244786,
    posterPath: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    title: "Whiplash",
    year: 2014,
    genre: ["Drama", "Music"],
    director: "Damien Chazelle",
    runtime: 107,
    description:
      "A promising young drummer enrolls at a cut-throat music conservatory where his teacher will stop at nothing to realize a student's potential.",
    cast: [
      "Miles Teller",
      "J.K. Simmons",
      "Melissa Benoist",
      "Paul Reiser",
      "Austin Stowell",
    ],
  },
  {
    id: "m11",
    tmdbId: 546554,
    posterPath: "/pThyQovXQrws2hmsbpQa3XrzmxM.jpg",
    title: "Knives Out",
    year: 2019,
    genre: ["Mystery", "Comedy", "Drama"],
    director: "Rian Johnson",
    runtime: 130,
    description:
      "A detective investigates the death of a patriarch of an eccentric, combative family.",
    cast: [
      "Daniel Craig",
      "Ana de Armas",
      "Chris Evans",
      "Jamie Lee Curtis",
      "Michael Shannon",
      "Toni Collette",
    ],
  },
  {
    id: "m12",
    tmdbId: 530915,
    posterPath: "/iZf0KyrE25z1sage4SYQLNjmKtM.jpg",
    title: "1917",
    year: 2019,
    genre: ["War", "Drama", "Action"],
    director: "Sam Mendes",
    runtime: 119,
    description:
      "Two British soldiers must cross enemy territory to deliver a message that could prevent a massacre during World War I.",
    cast: [
      "George MacKay",
      "Dean-Charles Chapman",
      "Mark Strong",
      "Andrew Scott",
      "Richard Madden",
      "Colin Firth",
    ],
  },
  {
    id: "m13",
    tmdbId: 238,
    posterPath: "/3bhkrj58Vtu7enYsLegHnDcdh9b.jpg",
    title: "The Godfather",
    year: 1972,
    genre: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    runtime: 175,
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    cast: [
      "Marlon Brando",
      "Al Pacino",
      "James Caan",
      "Diane Keaton",
      "Robert Duvall",
      "Talia Shire",
    ],
  },
  {
    id: "m14",
    tmdbId: 792307,
    posterPath: "/kCGlIMHnOm8JPXNbM7oi3AzGl1A.jpg",
    title: "Poor Things",
    year: 2023,
    genre: ["Drama", "Comedy", "Sci-Fi"],
    director: "Yorgos Lanthimos",
    runtime: 141,
    description:
      "The incredible tale about the evolution of Bella Baxter, a young woman brought back to life by the brilliant Dr. Godwin Baxter.",
    cast: [
      "Emma Stone",
      "Mark Ruffalo",
      "Willem Dafoe",
      "Ramy Youssef",
      "Margaret Qualley",
    ],
  },
  {
    id: "m15",
    tmdbId: 493922,
    posterPath: "/AQPP4T6dSBRLXmAAbhbEQbzHoP.jpg",
    title: "Hereditary",
    year: 2018,
    genre: ["Horror", "Drama", "Mystery"],
    director: "Ari Aster",
    runtime: 127,
    description:
      "When the matriarch of the Graham family passes away, her daughter's family begins to unravel cryptic and terrifying secrets about their ancestry.",
    cast: [
      "Toni Collette",
      "Alex Wolff",
      "Milly Shapiro",
      "Gabriel Byrne",
      "Ann Dowd",
    ],
  },
  {
    id: "m16",
    tmdbId: 376867,
    posterPath: "/4911T5FbJ9eAlnGHsHp7930WFMF.jpg",
    title: "Moonlight",
    year: 2016,
    genre: ["Drama", "Romance"],
    director: "Barry Jenkins",
    runtime: 111,
    description:
      "A young African-American man grapples with his identity and sexuality across three defining chapters of his life in Miami.",
    cast: [
      "Trevante Rhodes",
      "André Holland",
      "Janelle Monáe",
      "Naomie Harris",
      "Mahershala Ali",
    ],
  },
  {
    id: "m17",
    tmdbId: 313369,
    posterPath: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    title: "La La Land",
    year: 2016,
    genre: ["Musical", "Romance", "Drama"],
    director: "Damien Chazelle",
    runtime: 128,
    description:
      "A pianist and an actress fall in love while chasing their dreams in Los Angeles, navigating the tension between art and ambition.",
    cast: [
      "Ryan Gosling",
      "Emma Stone",
      "John Legend",
      "Rosemarie DeWitt",
      "J.K. Simmons",
    ],
  },
  {
    id: "m18",
    tmdbId: 414906,
    posterPath: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    title: "The Batman",
    year: 2022,
    genre: ["Action", "Crime", "Drama"],
    director: "Matt Reeves",
    runtime: 176,
    description:
      "When a sadistic serial killer targets Gotham's elite, Batman investigates the city's hidden corruption and questions his family's legacy.",
    cast: [
      "Robert Pattinson",
      "Zoë Kravitz",
      "Paul Dano",
      "Jeffrey Wright",
      "Colin Farrell",
      "Andy Serkis",
    ],
  },
  {
    id: "m19",
    tmdbId: 578701,
    posterPath: "/3lnfXnOlm2S8FDNSMjK5DXTl1YF.jpg",
    title: "Portrait of a Lady on Fire",
    year: 2019,
    genre: ["Drama", "Romance", "History"],
    director: "Céline Sciamma",
    runtime: 122,
    description:
      "On an isolated island in 18th-century Brittany, a female painter falls in love with the subject of her portrait.",
    cast: ["Noémie Merlant", "Adèle Haenel", "Luàna Bajrami", "Valeria Golino"],
  },
  {
    id: "m20",
    tmdbId: 278,
    posterPath: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    title: "The Shawshank Redemption",
    year: 1994,
    genre: ["Drama", "Crime"],
    director: "Frank Darabont",
    runtime: 142,
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    cast: [
      "Tim Robbins",
      "Morgan Freeman",
      "Bob Gunton",
      "William Sadler",
      "Clancy Brown",
    ],
  },
];
export const shows: Show[] = [
  {
    id: "s1",
    tmdbId: 1396,
    posterPath: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    title: "Breaking Bad",
    year: 2008,
    seasons: 5,
    status: "ended",
    network: "AMC",
    genre: ["Crime", "Drama", "Thriller"],
    description:
      "A high school chemistry teacher turned meth manufacturer partners with a former student to secure his family's financial future as he faces terminal cancer.",
    cast: [
      "Bryan Cranston",
      "Aaron Paul",
      "Anna Gunn",
      "Dean Norris",
      "Bob Odenkirk",
      "Giancarlo Esposito",
    ],
  },
  {
    id: "s2",
    tmdbId: 136315,
    posterPath: "/sYNZqi9oeScABBm7pBqrpLSXv6k.jpg",
    title: "The Bear",
    year: 2022,
    seasons: 3,
    status: "ongoing",
    network: "FX",
    genre: ["Drama", "Comedy"],
    description:
      "A young chef from the fine dining world comes home to Chicago to run his family's chaotic sandwich shop.",
    cast: [
      "Jeremy Allen White",
      "Ebon Moss-Bachrach",
      "Ayo Edebiri",
      "Lionel Boyce",
      "Liza Colón-Zayas",
    ],
  },
  {
    id: "s3",
    tmdbId: 63351,
    posterPath: "/r0UBDp3WmSt8vO76M7nXH4GJnJM.jpg",
    title: "Succession",
    year: 2018,
    seasons: 4,
    status: "ended",
    network: "HBO",
    genre: ["Drama", "Comedy"],
    description:
      "The Roy family controls a global media empire. When the patriarch's health falters, a brutal succession war tears the family apart.",
    cast: [
      "Brian Cox",
      "Jeremy Strong",
      "Kieran Culkin",
      "Sarah Snook",
      "Matthew Macfadyen",
      "Nicholas Braun",
    ],
  },
  {
    id: "s4",
    tmdbId: 95396,
    posterPath: "/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg",
    title: "Severance",
    year: 2022,
    seasons: 2,
    status: "ongoing",
    network: "Apple TV+",
    genre: ["Sci-Fi", "Drama", "Mystery"],
    description:
      "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.",
    cast: [
      "Adam Scott",
      "Patricia Arquette",
      "John Turturro",
      "Britt Lower",
      "Zach Cherry",
      "Tramell Tillman",
    ],
  },
  {
    id: "s5",
    tmdbId: 100088,
    posterPath: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    title: "The Last of Us",
    year: 2023,
    seasons: 2,
    status: "ongoing",
    network: "HBO",
    genre: ["Drama", "Horror", "Sci-Fi"],
    description:
      "After a global catastrophe, a hardened smuggler takes charge of a teenage girl who may be humanity's last hope.",
    cast: [
      "Pedro Pascal",
      "Bella Ramsey",
      "Anna Torv",
      "Nick Offerman",
      "Melanie Lynskey",
      "Storm Reid",
    ],
  },
  {
    id: "s6",
    tmdbId: 85552,
    posterPath: "/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
    title: "Euphoria",
    year: 2019,
    seasons: 3,
    status: "ongoing",
    network: "HBO",
    genre: ["Drama"],
    description:
      "A group of high school students navigate love, identity, trauma, drugs, and social media in a hyper-saturated world.",
    cast: [
      "Zendaya",
      "Hunter Schafer",
      "Jacob Elordi",
      "Sydney Sweeney",
      "Maude Apatow",
      "Eric Dane",
    ],
  },
  {
    id: "s7",
    tmdbId: 87108,
    posterPath: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    title: "Chernobyl",
    year: 2019,
    seasons: 1,
    status: "ended",
    network: "HBO",
    genre: ["Drama", "History", "Thriller"],
    description:
      "In April 1986, the Chernobyl nuclear disaster unfolds — and the Soviet state works to contain not just the reactor, but the truth.",
    cast: [
      "Jared Harris",
      "Stellan Skarsgård",
      "Emily Watson",
      "Paul Ritter",
      "David Dencik",
    ],
  },
  {
    id: "s8",
    tmdbId: 73492,
    posterPath: "/7v4S3YHrxHa7aEFlbNQ7dWpzr0N.jpg",
    title: "Barry",
    year: 2018,
    seasons: 4,
    status: "ended",
    network: "HBO",
    genre: ["Crime", "Comedy", "Drama"],
    description:
      "A depressed hitman from the Midwest moves to Los Angeles and gets mixed up with aspiring actors — and can't escape either world.",
    cast: [
      "Bill Hader",
      "Henry Winkler",
      "Anthony Carrigan",
      "Sarah Goldberg",
      "Stephen Root",
    ],
  },
  {
    id: "s9",
    tmdbId: 66586,
    posterPath: "/z3VBHkNUJDyuTeBBMONrM5VmxcH.jpg",
    title: "Atlanta",
    year: 2016,
    seasons: 4,
    status: "ended",
    network: "FX",
    genre: ["Comedy", "Drama", "Music"],
    description:
      "Two cousins work through the Atlanta rap scene in order to improve their lives, navigating a surreal city full of strange people.",
    cast: [
      "Donald Glover",
      "Brian Tyree Henry",
      "LaKeith Stanfield",
      "Zazie Beetz",
    ],
  },
  {
    id: "s10",
    tmdbId: 60059,
    posterPath: "/faHZIiNiOCHl0U5GYGN1NtY8LiF.jpg",
    title: "Better Call Saul",
    year: 2015,
    seasons: 6,
    status: "ended",
    network: "AMC",
    genre: ["Crime", "Drama"],
    description:
      "The story of Jimmy McGill's transformation into criminal lawyer Saul Goodman in the years before Breaking Bad.",
    cast: [
      "Bob Odenkirk",
      "Rhea Seehorn",
      "Jonathan Banks",
      "Giancarlo Esposito",
      "Michael Mando",
    ],
  },
  {
    id: "s11",
    tmdbId: 113988,
    posterPath: "/dZVbXRoNASCDgVFuZFMDpPVjOr8.jpg",
    title: "The White Lotus",
    year: 2021,
    seasons: 3,
    status: "ongoing",
    network: "HBO",
    genre: ["Drama", "Mystery", "Comedy"],
    description:
      "A social satire following guests and employees of an exclusive resort. Each season, a new location, new guests, new secrets.",
    cast: [
      "Jennifer Coolidge",
      "Murray Bartlett",
      "Connie Britton",
      "Sydney Sweeney",
      "Alexandra Daddario",
    ],
  },
  {
    id: "s12",
    tmdbId: 83867,
    posterPath: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
    title: "Andor",
    year: 2022,
    seasons: 2,
    status: "ongoing",
    network: "Disney+",
    genre: ["Sci-Fi", "Action", "Drama"],
    description:
      "The gritty origin story of rebel spy Cassian Andor and the formation of the Rebel Alliance — the best Star Wars has to offer.",
    cast: [
      "Diego Luna",
      "Genevieve O'Reilly",
      "Stellan Skarsgård",
      "Fiona Shaw",
      "Kyle Soller",
    ],
  },
  {
    id: "s13",
    tmdbId: 94997,
    posterPath: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    title: "House of the Dragon",
    year: 2022,
    seasons: 2,
    status: "ongoing",
    network: "HBO",
    genre: ["Fantasy", "Drama", "Action"],
    description:
      "Set 200 years before Game of Thrones — the Targaryen civil war that nearly destroyed the dragon riders.",
    cast: [
      "Paddy Considine",
      "Matt Smith",
      "Olivia Cooke",
      "Emma D'Arcy",
      "Rhys Ifans",
      "Steve Toussaint",
    ],
  },
  {
    id: "s14",
    tmdbId: 125988,
    posterPath: "/pqzjCxPVc9HHPDSelIVTjF7mDsS.jpg",
    title: "Silo",
    year: 2023,
    seasons: 2,
    status: "ongoing",
    network: "Apple TV+",
    genre: ["Sci-Fi", "Drama", "Mystery"],
    description:
      "In a ruined and toxic future, thousands live underground in a giant silo. One woman dares to ask why.",
    cast: [
      "Rebecca Ferguson",
      "Common",
      "David Oyelowo",
      "Tim Robbins",
      "Harriet Walter",
    ],
  },
  {
    id: "s15",
    tmdbId: 114288,
    posterPath: "/hFa9pBsKOBMcF1IIIh4bnnwxgpW.jpg",
    title: "Slow Horses",
    year: 2022,
    seasons: 4,
    status: "ongoing",
    network: "Apple TV+",
    genre: ["Thriller", "Drama", "Crime"],
    description:
      "Britain's cast-off spies, working from a dumping-ground MI5 desk called Slough House, get tangled in a live terrorist plot.",
    cast: [
      "Gary Oldman",
      "Jack Lowden",
      "Kristin Scott Thomas",
      "Olivia Cooke",
      "Saskia Reeves",
    ],
  },
];
export const myMovieRatings: MovieRating[] = [
  {
    id: "mr1",
    userId: "u1",
    movie: movies[1],
    rating: 9.5,
    review: "The Joker is cinema.",
    dateWatched: "2024-01-15",
    isFavorite: true,
  },
  {
    id: "mr2",
    userId: "u1",
    movie: movies[0],
    rating: 9.2,
    review: "Layers on layers. Never gets old.",
    dateWatched: "2023-11-20",
  },
  {
    id: "mr3",
    userId: "u1",
    movie: movies[12],
    rating: 9.3,
    review: "The standard everything gets measured against.",
    dateWatched: "2023-09-05",
  },
  {
    id: "mr4",
    userId: "u1",
    movie: movies[9],
    rating: 9.1,
    review: "Fletcher is terrifying. The ending destroyed me.",
    dateWatched: "2024-02-01",
  },
  {
    id: "mr5",
    userId: "u1",
    movie: movies[3],
    rating: 9.0,
    review: "Perfect structure, perfect ending. Bong is a genius.",
    dateWatched: "2023-07-10",
  },
  {
    id: "mr6",
    userId: "u1",
    movie: movies[5],
    rating: 8.7,
    review: "Genuinely unlike anything else.",
    dateWatched: "2023-12-12",
  },
  {
    id: "mr7",
    userId: "u1",
    movie: movies[2],
    rating: 8.8,
    review: "Hans Zimmer does half the work but earns it.",
    dateWatched: "2024-01-03",
  },
  {
    id: "mr8",
    userId: "u1",
    movie: movies[4],
    rating: 8.5,
    review: "Could've been 30 mins shorter. Still great.",
    dateWatched: "2023-08-21",
  },
  {
    id: "mr9",
    userId: "u1",
    movie: movies[11],
    rating: 8.6,
    review: "The one-shot gimmick earns every second.",
    dateWatched: "2023-10-30",
  },
  {
    id: "mr10",
    userId: "u1",
    movie: movies[8],
    rating: 8.4,
    review: "Jordan Peele is a master of making you squirm.",
    dateWatched: "2023-06-15",
  },
  {
    id: "mr11",
    userId: "u1",
    movie: movies[6],
    rating: 8.0,
    review: "Visually stunning. Patient and rewarding.",
    dateWatched: "2024-03-08",
  },
  {
    id: "mr12",
    userId: "u1",
    movie: movies[10],
    rating: 7.8,
    review: "Clever, witty, and replayable.",
    dateWatched: "2023-05-22",
  },
  {
    id: "mr13",
    userId: "u1",
    movie: movies[13],
    rating: 7.5,
    review: "Weird and wild. Lanthimos stays Lanthimos.",
    dateWatched: "2024-01-28",
  },
];
export const myShowRatings: ShowRating[] = [
  {
    id: "sr1",
    userId: "u1",
    show: shows[0],
    overallRating: 9.8,
    seasonRatings: [
      { season: 1, rating: 9.0 },
      { season: 2, rating: 9.5 },
      { season: 3, rating: 9.7 },
      { season: 4, rating: 9.8 },
      { season: 5, rating: 9.9 },
    ],
    dateWatched: "2022-08-12",
    isFavorite: true,
  },
  {
    id: "sr2",
    userId: "u1",
    show: shows[2],
    overallRating: 9.2,
    seasonRatings: [
      { season: 1, rating: 8.5 },
      { season: 2, rating: 9.0 },
      { season: 3, rating: 9.3 },
      { season: 4, rating: 9.8 },
    ],
    dateWatched: "2023-05-28",
  },
  {
    id: "sr3",
    userId: "u1",
    show: shows[6],
    overallRating: 9.4,
    seasonRatings: [{ season: 1, rating: 9.4 }],
    dateWatched: "2023-04-14",
  },
  {
    id: "sr4",
    userId: "u1",
    show: shows[1],
    overallRating: 9.0,
    seasonRatings: [
      { season: 1, rating: 9.2 },
      { season: 2, rating: 9.0 },
      { season: 3, rating: 8.7 },
    ],
    dateWatched: "2024-06-10",
  },
  {
    id: "sr5",
    userId: "u1",
    show: shows[3],
    overallRating: 8.9,
    seasonRatings: [
      { season: 1, rating: 8.8 },
      { season: 2, rating: 9.1 },
    ],
    dateWatched: "2024-02-20",
  },
  {
    id: "sr6",
    userId: "u1",
    show: shows[7],
    overallRating: 8.7,
    seasonRatings: [
      { season: 1, rating: 8.5 },
      { season: 2, rating: 8.7 },
      { season: 3, rating: 9.0 },
      { season: 4, rating: 9.0 },
    ],
    dateWatched: "2023-09-01",
  },
  {
    id: "sr7",
    userId: "u1",
    show: shows[4],
    overallRating: 8.5,
    seasonRatings: [{ season: 1, rating: 8.5 }],
    dateWatched: "2023-03-18",
  },
  {
    id: "sr8",
    userId: "u1",
    show: shows[10],
    overallRating: 8.3,
    seasonRatings: [
      { season: 1, rating: 8.0 },
      { season: 2, rating: 8.5 },
    ],
    dateWatched: "2023-11-10",
  },
  {
    id: "sr9",
    userId: "u1",
    show: shows[8],
    overallRating: 8.6,
    seasonRatings: [
      { season: 1, rating: 8.6 },
      { season: 2, rating: 9.0 },
      { season: 3, rating: 8.0 },
      { season: 4, rating: 8.0 },
    ],
    dateWatched: "2023-02-05",
  },
];
const now = new Date();
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 3_600_000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 86_400_000).toISOString();
const daysFromNow = (d: number) =>
  new Date(now.getTime() + d * 86_400_000).toISOString();
export const feedActivities: FeedActivity[] = [
  {
    id: "fa1",
    user: friends[0],
    type: "movie_rating",
    movie: movies[7],
    rating: 9.1,
    review: "Zendaya carried this movie on her back.",
    timestamp: hoursAgo(2),
    reactions: { "🔥": ["u1", "u3"], "❤️": ["u4"], "👏": ["u5"] },
    comments: [
      {
        id: "c1",
        userId: "u3",
        user: friends[1],
        text: "So good, Nolan at his best",
        timestamp: hoursAgo(1),
      },
    ],
  },
  {
    id: "fa2",
    user: friends[2],
    type: "movie_rating",
    movie: movies[15],
    rating: 9.5,
    timestamp: hoursAgo(5),
    reactions: { "❤️": ["u2", "u1"], "😭": ["u5"] },
    comments: [
      {
        id: "c2",
        userId: "u2",
        user: friends[0],
        text: "Emma Stone was incredible in this",
        timestamp: hoursAgo(3),
      },
      {
        id: "c3",
        userId: "u5",
        user: friends[3],
        text: "Need to rewatch this asap",
        timestamp: hoursAgo(2),
      },
    ],
  },
  {
    id: "fa3",
    user: friends[1],
    type: "watchlist_add",
    show: shows[14],
    timestamp: hoursAgo(8),
    reactions: { "👍": ["u1"] },
  },
  {
    id: "fa4",
    user: friends[3],
    type: "movie_rating",
    movie: movies[14],
    rating: 9.0,
    review: "First 45 mins is one of the best horror setups ever.",
    timestamp: hoursAgo(14),
    reactions: { "🔥": ["u2", "u3", "u4"] },
  },
  {
    id: "fa5",
    user: friends[1],
    type: "show_rating",
    show: shows[11],
    rating: 9.3,
    seasonRatings: [
      { season: 1, rating: 9.5 },
      { season: 2, rating: 9.1 },
    ],
    review: "Best Star Wars content since the OT.",
    timestamp: hoursAgo(22),
    reactions: { "🔥": ["u1", "u5"], "❤️": ["u4"] },
  },
  {
    id: "fa6",
    user: friends[0],
    type: "movie_rating",
    movie: movies[13],
    rating: 7.2,
    review: "Liked it but didn't love it. Lanthimos fan tax.",
    timestamp: hoursAgo(36),
    reactions: { "😂": ["u3"] },
  },
  {
    id: "fa7",
    user: friends[1],
    type: "show_rating",
    show: shows[1],
    rating: 8.5,
    seasonRatings: [{ season: 3, rating: 8.5 }],
    timestamp: hoursAgo(48),
    reactions: { "👏": ["u1", "u2"] },
  },
  {
    id: "fa8",
    user: friends[3],
    type: "watchlist_add",
    show: shows[13],
    timestamp: hoursAgo(60),
    reactions: {},
  },
  {
    id: "fa9",
    user: friends[2],
    type: "rec_request",
    recQuery:
      "Something like Succession but darker and more cynical — totally hooked on that genre",
    recGenres: ["Drama", "Thriller"],
    timestamp: hoursAgo(3),
    reactions: { "❤️": ["u1"], "👍": ["u3"] },
    comments: [
      {
        id: "c4",
        userId: "u5",
        user: friends[3],
        text: "Miniseries: The Regime. Or try Borgen on Netflix",
        timestamp: hoursAgo(1),
      },
    ],
  },
  {
    id: "fa10",
    user: friends[0],
    type: "rec_request",
    recQuery: "Best horror movies from the last 5 years — go!",
    recGenres: ["Horror"],
    timestamp: hoursAgo(20),
    reactions: { "🔥": ["u3", "u5"] },
    comments: [
      {
        id: "c5",
        userId: "u5",
        user: friends[3],
        text: "Hereditary, no contest",
        timestamp: hoursAgo(18),
      },
      {
        id: "c6",
        userId: "u3",
        user: friends[1],
        text: "Talk to Me was insane",
        timestamp: hoursAgo(16),
      },
    ],
  },
];
export const communityMovies: CommunityItem[] = [
  {
    movie: movies[12],
    averageRating: 9.7,
    ratingCount: 1842,
    rank: 1,
    pct9plus: 91,
  },
  {
    movie: movies[1],
    averageRating: 9.6,
    ratingCount: 2103,
    rank: 2,
    pct9plus: 88,
  },
  {
    movie: movies[3],
    averageRating: 9.3,
    ratingCount: 1654,
    rank: 3,
    pct9plus: 85,
  },
  {
    movie: movies[19],
    averageRating: 9.2,
    ratingCount: 1291,
    rank: 4,
    pct9plus: 87,
  },
  {
    movie: movies[0],
    averageRating: 9.1,
    ratingCount: 1977,
    rank: 5,
    pct9plus: 83,
  },
  {
    movie: movies[9],
    averageRating: 9.0,
    ratingCount: 1103,
    rank: 6,
    pct9plus: 82,
  },
  {
    movie: movies[5],
    averageRating: 8.9,
    ratingCount: 987,
    rank: 7,
    pct9plus: 79,
  },
  {
    movie: movies[2],
    averageRating: 8.8,
    ratingCount: 1820,
    rank: 8,
    pct9plus: 81,
  },
  {
    movie: movies[4],
    averageRating: 8.7,
    ratingCount: 1543,
    rank: 9,
    pct9plus: 78,
  },
  {
    movie: movies[7],
    averageRating: 8.6,
    ratingCount: 1234,
    rank: 10,
    pct9plus: 76,
  },
];
export const communityShows: CommunityItem[] = [
  {
    show: shows[0],
    averageRating: 9.7,
    ratingCount: 2210,
    rank: 1,
    pct9plus: 94,
  },
  {
    show: shows[6],
    averageRating: 9.5,
    ratingCount: 1654,
    rank: 2,
    pct9plus: 90,
  },
  {
    show: shows[2],
    averageRating: 9.4,
    ratingCount: 1987,
    rank: 3,
    pct9plus: 87,
  },
  {
    show: shows[3],
    averageRating: 9.2,
    ratingCount: 1102,
    rank: 4,
    pct9plus: 85,
  },
  {
    show: shows[1],
    averageRating: 9.1,
    ratingCount: 1321,
    rank: 5,
    pct9plus: 82,
  },
  {
    show: shows[9],
    averageRating: 9.0,
    ratingCount: 1103,
    rank: 6,
    pct9plus: 81,
  },
  {
    show: shows[7],
    averageRating: 8.9,
    ratingCount: 875,
    rank: 7,
    pct9plus: 79,
  },
  {
    show: shows[4],
    averageRating: 8.8,
    ratingCount: 1441,
    rank: 8,
    pct9plus: 80,
  },
  {
    show: shows[11],
    averageRating: 8.7,
    ratingCount: 987,
    rank: 9,
    pct9plus: 78,
  },
  {
    show: shows[8],
    averageRating: 8.5,
    ratingCount: 765,
    rank: 10,
    pct9plus: 74,
  },
];
export const communitySeasons: CommunityItem[] = [
  { show: shows[0], season: 5, averageRating: 9.9, ratingCount: 1987, rank: 1 },
  { show: shows[2], season: 4, averageRating: 9.8, ratingCount: 1821, rank: 2 },
  { show: shows[6], season: 1, averageRating: 9.7, ratingCount: 1654, rank: 3 },
  { show: shows[0], season: 4, averageRating: 9.6, ratingCount: 1790, rank: 4 },
  { show: shows[1], season: 1, averageRating: 9.5, ratingCount: 1321, rank: 5 },
  { show: shows[3], season: 2, averageRating: 9.4, ratingCount: 1102, rank: 6 },
  { show: shows[11], season: 1, averageRating: 9.4, ratingCount: 987, rank: 7 },
  { show: shows[1], season: 2, averageRating: 9.2, ratingCount: 1201, rank: 8 },
  { show: shows[7], season: 3, averageRating: 9.1, ratingCount: 875, rank: 9 },
  {
    show: shows[4],
    season: 1,
    averageRating: 9.0,
    ratingCount: 1441,
    rank: 10,
  },
];
export const searchableMovies: Movie[] = [...movies];
export const searchableShows: Show[] = [...shows];
export const genres: string[] = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "History",
  "Horror",
  "Music",
  "Musical",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "War",
];
export const tasteMatchPercentages: Record<string, number> = {
  u2: 87,
  u3: 74,
  u4: 62,
  u5: 79,
};
const wlNow = new Date();
export const initialWatchlist: WatchlistItem[] = [
  {
    id: "wl1",
    contentType: "show",
    show: shows[14],
    addedDate: new Date(wlNow.getTime() - 86400000 * 2).toISOString(),
    recommendedBy: "friends",
  },
  {
    id: "wl2",
    contentType: "movie",
    movie: movies[18],
    addedDate: new Date(wlNow.getTime() - 86400000 * 5).toISOString(),
    recommendedBy: "taste",
  },
  {
    id: "wl3",
    contentType: "movie",
    movie: movies[7],
    addedDate: new Date(wlNow.getTime() - 86400000 * 9).toISOString(),
    recommendedBy: "community",
  },
];
export const friendsMovieRatings: Record<
  string,
  { userId: string; rating: number; review?: string }[]
> = {
  m1: [
    { userId: "u2", rating: 8.9, review: "Dream logic at its finest." },
    { userId: "u3", rating: 9.0 },
  ],
  m2: [
    {
      userId: "u3",
      rating: 9.8,
      review: "Heath Ledger gave the performance of a generation.",
    },
    { userId: "u5", rating: 9.4 },
  ],
  m4: [
    {
      userId: "u4",
      rating: 9.2,
      review: "Changed how I think about class in film.",
    },
    { userId: "u2", rating: 8.8 },
  ],
  m5: [
    { userId: "u3", rating: 8.2 },
    { userId: "u4", rating: 7.9, review: "Incredible but too long for me." },
  ],
  m7: [
    {
      userId: "u2",
      rating: 9.1,
      review: "Zendaya carried this movie on her back.",
    },
  ],
  m9: [
    {
      userId: "u5",
      rating: 9.0,
      review: "First 45 mins is one of the best horror setups ever.",
    },
  ],
  m14: [
    {
      userId: "u2",
      rating: 7.2,
      review: "Liked it but didn't love it. Lanthimos fan tax.",
    },
  ],
  m15: [
    { userId: "u5", rating: 9.0 },
    { userId: "u2", rating: 8.7 },
  ],
};
export const friendsShowRatings: Record<
  string,
  { userId: string; rating: number; review?: string }[]
> = {
  s1: [
    {
      userId: "u3",
      rating: 9.9,
      review: "The greatest TV show ever made. Not up for debate.",
    },
  ],
  s2: [
    { userId: "u4", rating: 8.7 },
    { userId: "u2", rating: 9.0, review: "S1 is perfect television." },
  ],
  s3: [
    { userId: "u2", rating: 9.5, review: "The finale destroyed me." },
    { userId: "u3", rating: 8.9 },
  ],
  s12: [
    {
      userId: "u3",
      rating: 9.3,
      review: "Best Star Wars content since the original trilogy.",
    },
  ],
};
export const initialNotifications: Notification[] = [
  {
    id: "n1",
    type: "recommendation",
    fromUserId: "u2",
    fromUser: friends[0],
    show: shows[3],
    message: "You need to watch this NOW, trust me",
    timestamp: hoursAgo(3),
    seen: false,
  },
  {
    id: "n2",
    type: "recommendation",
    fromUserId: "u5",
    fromUser: friends[3],
    movie: movies[9],
    message: "This is exactly your vibe",
    timestamp: hoursAgo(18),
    seen: false,
  },
];

// ─── New & Upcoming ───────────────────────────────────────────────────────────

export const upcomingMovieStubs: Movie[] = [
  {
    id: "um1",
    title: "Sinners",
    year: 2025,
    genre: ["Horror", "Drama"],
    posterPath: "/y4cBBgFHv2H4YNcBjSVmPIfXfmD.jpg",
    runtime: 137,
  },
  {
    id: "um2",
    title: "A Minecraft Movie",
    year: 2025,
    genre: ["Adventure", "Comedy"],
    posterPath: "/iPPTGh1xPaDMBLOiYFq7qhEkwsB.jpg",
    runtime: 101,
  },
  {
    id: "um3",
    title: "The Accountant 2",
    year: 2025,
    genre: ["Action", "Thriller"],
    posterPath: "/6Tojm5HnFpqzWtWrJ52PqPPOBMu.jpg",
    runtime: 122,
  },
  {
    id: "um4",
    title: "Mission: Impossible 8",
    year: 2025,
    genre: ["Action", "Thriller"],
    posterPath: "/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
    runtime: null as unknown as number,
  },
  {
    id: "um5",
    title: "Materialists",
    year: 2025,
    genre: ["Romance", "Drama"],
    posterPath: "/wcA4T7QdFJoA9JaXaqbOoKTWjS3.jpg",
    runtime: null as unknown as number,
  },
  {
    id: "um6",
    title: "Novocaine",
    year: 2025,
    genre: ["Action", "Comedy"],
    posterPath: "/1YMHKdFGHFqoE3mDxm7m7sM9GIJY.jpg",
    runtime: 110,
  },
];

export const nowPlaying: NowPlayingMovie[] = [
  { movie: movies[7], inTheatersDate: daysAgo(21), buzz: "Still packing theaters worldwide." },
  {
    movie: upcomingMovieStubs[0],
    inTheatersDate: daysAgo(14),
    buzz: "Ryan Coogler's vampire epic. Go in blind.",
  },
  { movie: upcomingMovieStubs[1], inTheatersDate: daysAgo(10), buzz: "Bigger than anyone expected." },
  {
    movie: upcomingMovieStubs[2],
    inTheatersDate: daysAgo(7),
    buzz: "Ben Affleck's back. Better than the first.",
  },
  {
    movie: upcomingMovieStubs[5],
    inTheatersDate: daysAgo(3),
    buzz: "Jack Quaid breaks bones and takes names.",
  },
  { movie: movies[5], inTheatersDate: daysAgo(28), buzz: "Re-release with 4K remaster." },
];

export const comingSoon: UpcomingMovie[] = [
  {
    movie: upcomingMovieStubs[3],
    releaseDate: daysFromNow(18),
    buzz: "Tom Cruise's last ride. For real this time.",
  },
  {
    movie: upcomingMovieStubs[4],
    releaseDate: daysFromNow(35),
    buzz: "Celine Song follows up Past Lives.",
  },
  {
    movie: movies[4],
    releaseDate: daysFromNow(42),
    buzz: "Director's cut re-release. 30 extra minutes.",
  },
  { movie: movies[8], releaseDate: daysFromNow(60), buzz: "Jordan Peele's follow-up to Nope." },
];

// ─── New & Returning Shows ────────────────────────────────────────────────────

export const newShowStubs: Show[] = [
  {
    id: "ns1",
    title: "The Pitt",
    year: 2025,
    seasons: 1,
    status: "ongoing",
    network: "Max",
    genre: ["Drama"],
    posterPath: "/5gUGcfJPDMEzKBj8GbyMaCO3CbB.jpg",
  },
  {
    id: "ns2",
    title: "Adolescence",
    year: 2025,
    seasons: 1,
    status: "ongoing",
    network: "Netflix",
    genre: ["Drama", "Thriller"],
    posterPath: "/eNn4xhVEhJXvWrQdJwmHJKrSGcX.jpg",
  },
  {
    id: "ns3",
    title: "Daredevil: Born Again",
    year: 2025,
    seasons: 1,
    status: "ongoing",
    network: "Disney+",
    genre: ["Action", "Crime", "Drama"],
    posterPath: "/yT1TXP8vBCbmA21BWWB9nZ6Nq9l.jpg",
  },
  {
    id: "ns4",
    title: "The Last of Us S2",
    year: 2025,
    seasons: 2,
    status: "ongoing",
    network: "HBO",
    genre: ["Drama", "Horror", "Sci-Fi"],
    posterPath: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
  },
];

export const nowStreaming: NowStreamingEntry[] = [
  {
    movie: movies[4],
    platform: "Max",
    arrivedDate: daysAgo(5),
    buzz: "Includes 30 minutes of additional footage.",
  },
  {
    movie: movies[5],
    platform: "Netflix",
    arrivedDate: daysAgo(12),
    buzz: "Remastered in 4K. Looks insane on a big screen.",
  },
  {
    movie: upcomingMovieStubs[2],
    platform: "Prime Video",
    arrivedDate: daysAgo(18),
    buzz: "Ben Affleck's action comeback — better than expected.",
  },
  {
    movie: movies[11],
    platform: "Apple TV+",
    arrivedDate: daysAgo(25),
    buzz: "One of the great war films. Perfect for a Sunday.",
  },
  {
    movie: movies[3],
    platform: "Max",
    arrivedDate: daysAgo(30),
    buzz: "If you still haven't seen Parasite, tonight's the night.",
  },
];

// ─── Friends Now Watching ─────────────────────────────────────────────────────

export const friendsNowWatching: (NowWatching & { user: User })[] = [
  {
    userId: "u2",
    user: friends[0],
    title: "Andor",
    type: "show",
    episode: "S2E3",
    startedAt: hoursAgo(1),
  },
  {
    userId: "u3",
    user: friends[1],
    title: "Dune: Part Two",
    type: "movie",
    startedAt: hoursAgo(3),
  },
  {
    userId: "u4",
    user: friends[2],
    title: "The Bear",
    type: "show",
    episode: "S3E1",
    startedAt: hoursAgo(6),
  },
  {
    userId: "u5",
    user: friends[3],
    title: "Interstellar",
    type: "movie",
    startedAt: hoursAgo(12),
  },
];

export const newAndReturning: NewShowEntry[] = [
  {
    show: newShowStubs[1],
    type: "new-series",
    premiereDate: daysAgo(5),
    buzz: "Shot in one continuous take per episode. Netflix's biggest swing in years.",
  },
  {
    show: newShowStubs[2],
    type: "new-series",
    premiereDate: daysAgo(14),
    buzz: "Charlie Cox is finally back, and it's everything.",
  },
  {
    show: newShowStubs[3],
    type: "new-season",
    season: 2,
    premiereDate: daysFromNow(30),
    buzz: "The most anticipated TV return of 2025.",
  },
  {
    show: shows[3],
    type: "new-season",
    season: 2,
    premiereDate: daysAgo(28),
    buzz: "Severance S2 delivered. Every episode.",
  },
  {
    show: newShowStubs[0],
    type: "new-series",
    premiereDate: daysAgo(42),
    buzz: "Noah Wyle's ER successor is the real deal.",
  },
  {
    show: shows[10],
    type: "new-season",
    season: 3,
    premiereDate: daysFromNow(15),
    buzz: "Thailand. New cast. Same savage wit.",
  },
];

// ─── Friend Ratings (for taste comparison) ───────────────────────────────────

export interface FriendRating {
  title: string;
  type: "movie" | "show";
  year: number;
  rating: number;
}

export const friendRatings: Record<string, FriendRating[]> = {
  u2: [
    { title: "Dune: Part Two", type: "movie", year: 2024, rating: 9.5 },
    { title: "Hereditary", type: "movie", year: 2018, rating: 9.8 },
    { title: "Oppenheimer", type: "movie", year: 2023, rating: 8.2 },
    { title: "Parasite", type: "movie", year: 2019, rating: 9.4 },
    { title: "Succession", type: "show", year: 2018, rating: 9.5 },
    { title: "Moonlight", type: "movie", year: 2016, rating: 9.6 },
    { title: "The Batman", type: "movie", year: 2022, rating: 6.5 },
    { title: "Arrival", type: "movie", year: 2016, rating: 8.0 },
    { title: "Fleabag", type: "show", year: 2016, rating: 9.3 },
    { title: "Knives Out", type: "movie", year: 2019, rating: 7.8 },
  ],
  u3: [
    { title: "The Batman", type: "movie", year: 2022, rating: 9.2 },
    { title: "Dune: Part Two", type: "movie", year: 2024, rating: 9.0 },
    { title: "Mad Max: Fury Road", type: "movie", year: 2015, rating: 9.5 },
    { title: "Oppenheimer", type: "movie", year: 2023, rating: 8.4 },
    { title: "Arcane", type: "show", year: 2021, rating: 9.7 },
    { title: "Better Call Saul", type: "show", year: 2015, rating: 9.4 },
    { title: "Parasite", type: "movie", year: 2019, rating: 7.8 },
    { title: "Interstellar", type: "movie", year: 2014, rating: 9.8 },
    { title: "Spider-Man: Across the Spider-Verse", type: "movie", year: 2023, rating: 9.4 },
    { title: "Get Out", type: "movie", year: 2017, rating: 7.5 },
  ],
  u4: [
    { title: "Everything Everywhere All at Once", type: "movie", year: 2022, rating: 9.9 },
    { title: "Fleabag", type: "show", year: 2016, rating: 9.8 },
    { title: "Parasite", type: "movie", year: 2019, rating: 9.6 },
    { title: "Dune: Part Two", type: "movie", year: 2024, rating: 8.8 },
    { title: "Interstellar", type: "movie", year: 2014, rating: 9.5 },
    { title: "The Bear", type: "show", year: 2022, rating: 9.0 },
    { title: "Oppenheimer", type: "movie", year: 2023, rating: 8.4 },
    { title: "Arrival", type: "movie", year: 2016, rating: 9.2 },
    { title: "The Batman", type: "movie", year: 2022, rating: 5.5 },
    { title: "Knives Out", type: "movie", year: 2019, rating: 8.8 },
  ],
  u5: [
    { title: "The Grand Budapest Hotel", type: "movie", year: 2014, rating: 9.8 },
    { title: "Knives Out", type: "movie", year: 2019, rating: 9.2 },
    { title: "Dune: Part Two", type: "movie", year: 2024, rating: 7.5 },
    { title: "Oppenheimer", type: "movie", year: 2023, rating: 8.0 },
    { title: "The Office", type: "show", year: 2005, rating: 9.5 },
    { title: "Atlanta", type: "show", year: 2016, rating: 9.3 },
    { title: "Parasite", type: "movie", year: 2019, rating: 8.4 },
    { title: "Interstellar", type: "movie", year: 2014, rating: 7.8 },
    { title: "Arrival", type: "movie", year: 2016, rating: 8.5 },
    { title: "Spider-Man: Across the Spider-Verse", type: "movie", year: 2023, rating: 8.8 },
  ],
};
