import type {
  User,
  Show,
  ShowRating,
  FeedActivity,
  CommunityItem,
  WatchlistItem,
  Notification,
} from "./types";
export const currentUser: User = {
  id: "u1",
  name: "Gavin Ostrow",
  username: "gavin",
  bio: "TV is better with commentary you'll never share.",
  favoriteGenres: ["Sci-Fi", "Drama", "Thriller"],
};
export const friends: User[] = [
  {
    id: "u2",
    name: "Emma Chen",
    username: "emma_c",
    favoriteGenres: ["Drama", "Horror", "Romance"],
  },
  {
    id: "u3",
    name: "Marcus Williams",
    username: "marcusw",
    favoriteGenres: ["Sci-Fi", "Action", "Crime"],
  },
  {
    id: "u4",
    name: "Sofia Rodriguez",
    username: "sofia_r",
    favoriteGenres: ["Drama", "Comedy", "Musical"],
  },
  {
    id: "u5",
    name: "Jake Park",
    username: "jake_p",
    favoriteGenres: ["Horror", "Thriller", "Mystery"],
  },
  {
    id: "u6",
    name: "Michael Torres",
    username: "mtorres",
    favoriteGenres: ["Crime", "Drama", "Comedy"],
  },
];
export const shows: Show[] = [
  {
    id: "s1",
    tmdbId: 1396,
    posterPath: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    title: "Breaking Bad",
    year: 2008,
    seasons: 5,
    status: "ended",
    network: "AMC",
    genre: ["Crime", "Drama", "Thriller"],
    description:
      "A high school chemistry teacher turned meth manufacturer partners with a former student to secure his family's financial future as he faces terminal cancer.",
    cast: [
      "Bryan Cranston",
      "Aaron Paul",
      "Anna Gunn",
      "Dean Norris",
      "Bob Odenkirk",
      "Giancarlo Esposito",
    ],
  },
  {
    id: "s2",
    tmdbId: 136315,
    posterPath: "/sYNZqi9oeScABBm7pBqrpLSXv6k.jpg",
    title: "The Bear",
    year: 2022,
    seasons: 3,
    status: "ongoing",
    network: "FX",
    genre: ["Drama", "Comedy"],
    description:
      "A young chef from the fine dining world comes home to Chicago to run his family's chaotic sandwich shop.",
    cast: [
      "Jeremy Allen White",
      "Ebon Moss-Bachrach",
      "Ayo Edebiri",
      "Lionel Boyce",
      "Liza Colón-Zayas",
    ],
  },
  {
    id: "s3",
    tmdbId: 63351,
    posterPath: "/r0UBDp3WmSt8vO76M7nXH4GJnJM.jpg",
    title: "Succession",
    year: 2018,
    seasons: 4,
    status: "ended",
    network: "HBO",
    genre: ["Drama", "Comedy"],
    description:
      "The Roy family controls a global media empire. When the patriarch's health falters, a brutal succession war tears the family apart.",
    cast: [
      "Brian Cox",
      "Jeremy Strong",
      "Kieran Culkin",
      "Sarah Snook",
      "Matthew Macfadyen",
      "Nicholas Braun",
    ],
  },
  {
    id: "s4",
    tmdbId: 95396,
    posterPath: "/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg",
    title: "Severance",
    year: 2022,
    seasons: 2,
    status: "ongoing",
    network: "Apple TV+",
    genre: ["Sci-Fi", "Drama", "Mystery"],
    description:
      "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.",
    cast: [
      "Adam Scott",
      "Patricia Arquette",
      "John Turturro",
      "Britt Lower",
      "Zach Cherry",
      "Tramell Tillman",
    ],
  },
  {
    id: "s5",
    tmdbId: 100088,
    posterPath: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    title: "The Last of Us",
    year: 2023,
    seasons: 2,
    status: "ongoing",
    network: "HBO",
    genre: ["Drama", "Horror", "Sci-Fi"],
    description:
      "After a global catastrophe, a hardened smuggler takes charge of a teenage girl who may be humanity's last hope.",
    cast: [
      "Pedro Pascal",
      "Bella Ramsey",
      "Anna Torv",
      "Nick Offerman",
      "Melanie Lynskey",
      "Storm Reid",
    ],
  },
  {
    id: "s6",
    tmdbId: 85552,
    posterPath: "/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
    title: "Euphoria",
    year: 2019,
    seasons: 3,
    status: "ongoing",
    network: "HBO",
    genre: ["Drama"],
    description:
      "A group of high school students navigate love, identity, trauma, drugs, and social media in a hyper-saturated world.",
    cast: [
      "Zendaya",
      "Hunter Schafer",
      "Jacob Elordi",
      "Sydney Sweeney",
      "Maude Apatow",
      "Eric Dane",
    ],
  },
  {
    id: "s7",
    tmdbId: 87108,
    posterPath: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    title: "Chernobyl",
    year: 2019,
    seasons: 1,
    status: "ended",
    network: "HBO",
    genre: ["Drama", "History", "Thriller"],
    description:
      "In April 1986, the Chernobyl nuclear disaster unfolds — and the Soviet state works to contain not just the reactor, but the truth.",
    cast: [
      "Jared Harris",
      "Stellan Skarsgård",
      "Emily Watson",
      "Paul Ritter",
      "David Dencik",
    ],
  },
  {
    id: "s8",
    tmdbId: 73492,
    posterPath: "/7v4S3YHrxHa7aEFlbNQ7dWpzr0N.jpg",
    title: "Barry",
    year: 2018,
    seasons: 4,
    status: "ended",
    network: "HBO",
    genre: ["Crime", "Comedy", "Drama"],
    description:
      "A depressed hitman from the Midwest moves to Los Angeles and gets mixed up with aspiring actors — and can't escape either world.",
    cast: [
      "Bill Hader",
      "Henry Winkler",
      "Anthony Carrigan",
      "Sarah Goldberg",
      "Stephen Root",
    ],
  },
  {
    id: "s9",
    tmdbId: 66586,
    posterPath: "/z3VBHkNUJDyuTeBBMONrM5VmxcH.jpg",
    title: "Atlanta",
    year: 2016,
    seasons: 4,
    status: "ended",
    network: "FX",
    genre: ["Comedy", "Drama", "Music"],
    description:
      "Two cousins work through the Atlanta rap scene in order to improve their lives, navigating a surreal city full of strange people.",
    cast: [
      "Donald Glover",
      "Brian Tyree Henry",
      "LaKeith Stanfield",
      "Zazie Beetz",
    ],
  },
  {
    id: "s10",
    tmdbId: 60059,
    posterPath: "/faHZIiNiOCHl0U5GYGN1NtY8LiF.jpg",
    title: "Better Call Saul",
    year: 2015,
    seasons: 6,
    status: "ended",
    network: "AMC",
    genre: ["Crime", "Drama"],
    description:
      "The story of Jimmy McGill's transformation into criminal lawyer Saul Goodman in the years before Breaking Bad.",
    cast: [
      "Bob Odenkirk",
      "Rhea Seehorn",
      "Jonathan Banks",
      "Giancarlo Esposito",
      "Michael Mando",
    ],
  },
  {
    id: "s11",
    tmdbId: 113988,
    posterPath: "/dZVbXRoNASCDgVFuZFMDpPVjOr8.jpg",
    title: "The White Lotus",
    year: 2021,
    seasons: 3,
    status: "ongoing",
    network: "HBO",
    genre: ["Drama", "Mystery", "Comedy"],
    description:
      "A social satire following guests and employees of an exclusive resort. Each season, a new location, new guests, new secrets.",
    cast: [
      "Jennifer Coolidge",
      "Murray Bartlett",
      "Connie Britton",
      "Sydney Sweeney",
      "Alexandra Daddario",
    ],
  },
  {
    id: "s12",
    tmdbId: 83867,
    posterPath: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
    title: "Andor",
    year: 2022,
    seasons: 2,
    status: "ongoing",
    network: "Disney+",
    genre: ["Sci-Fi", "Action", "Drama"],
    description:
      "The gritty origin story of rebel spy Cassian Andor and the formation of the Rebel Alliance — the best Star Wars has to offer.",
    cast: [
      "Diego Luna",
      "Genevieve O'Reilly",
      "Stellan Skarsgård",
      "Fiona Shaw",
      "Kyle Soller",
    ],
  },
  {
    id: "s13",
    tmdbId: 94997,
    posterPath: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    title: "House of the Dragon",
    year: 2022,
    seasons: 2,
    status: "ongoing",
    network: "HBO",
    genre: ["Fantasy", "Drama", "Action"],
    description:
      "Set 200 years before Game of Thrones — the Targaryen civil war that nearly destroyed the dragon riders.",
    cast: [
      "Paddy Considine",
      "Matt Smith",
      "Olivia Cooke",
      "Emma D'Arcy",
      "Rhys Ifans",
      "Steve Toussaint",
    ],
  },
  {
    id: "s14",
    tmdbId: 125988,
    posterPath: "/pqzjCxPVc9HHPDSelIVTjF7mDsS.jpg",
    title: "Silo",
    year: 2023,
    seasons: 2,
    status: "ongoing",
    network: "Apple TV+",
    genre: ["Sci-Fi", "Drama", "Mystery"],
    description:
      "In a ruined and toxic future, thousands live underground in a giant silo. One woman dares to ask why.",
    cast: [
      "Rebecca Ferguson",
      "Common",
      "David Oyelowo",
      "Tim Robbins",
      "Harriet Walter",
    ],
  },
  {
    id: "s15",
    tmdbId: 114288,
    posterPath: "/hFa9pBsKOBMcF1IIIh4bnnwxgpW.jpg",
    title: "Slow Horses",
    year: 2022,
    seasons: 4,
    status: "ongoing",
    network: "Apple TV+",
    genre: ["Thriller", "Drama", "Crime"],
    description:
      "Britain's cast-off spies, working from a dumping-ground MI5 desk called Slough House, get tangled in a live terrorist plot.",
    cast: [
      "Gary Oldman",
      "Jack Lowden",
      "Kristin Scott Thomas",
      "Olivia Cooke",
      "Saskia Reeves",
    ],
  },
];
export const myShowRatings: ShowRating[] = [
  {
    id: "sr1",
    userId: "u1",
    show: shows[0],
    overallRating: 9.8,
    seasonRatings: [
      { season: 1, rating: 9.0 },
      { season: 2, rating: 9.5 },
      { season: 3, rating: 9.7 },
      { season: 4, rating: 9.8 },
      { season: 5, rating: 9.9 },
    ],
    dateWatched: "2026-01-25",
    isFavorite: true,
  },
  {
    id: "sr2",
    userId: "u1",
    show: shows[2],
    overallRating: 9.2,
    seasonRatings: [
      { season: 1, rating: 8.5 },
      { season: 2, rating: 9.0 },
      { season: 3, rating: 9.3 },
      { season: 4, rating: 9.8 },
    ],
    dateWatched: "2026-06-14",
  },
  {
    id: "sr3",
    userId: "u1",
    show: shows[6],
    overallRating: 9.4,
    seasonRatings: [{ season: 1, rating: 9.4 }],
    dateWatched: "2026-03-01",
  },
  {
    id: "sr4",
    userId: "u1",
    show: shows[1],
    overallRating: 9.0,
    seasonRatings: [
      { season: 1, rating: 9.2 },
      { season: 2, rating: 9.0 },
      { season: 3, rating: 8.7 },
    ],
    dateWatched: "2026-08-30",
  },
  {
    id: "sr5",
    userId: "u1",
    show: shows[3],
    overallRating: 8.9,
    seasonRatings: [
      { season: 1, rating: 8.8 },
      { season: 2, rating: 9.1 },
    ],
    dateWatched: "2026-05-09",
  },
  {
    id: "sr6",
    userId: "u1",
    show: shows[7],
    overallRating: 8.7,
    seasonRatings: [
      { season: 1, rating: 8.5 },
      { season: 2, rating: 8.7 },
      { season: 3, rating: 9.0 },
      { season: 4, rating: 9.0 },
    ],
    dateWatched: "2025-09-01",
  },
  {
    id: "sr7",
    userId: "u1",
    show: shows[4],
    overallRating: 8.5,
    seasonRatings: [{ season: 1, rating: 8.5 }],
    dateWatched: "2026-07-20",
  },
  {
    id: "sr8",
    userId: "u1",
    show: shows[10],
    overallRating: 8.3,
    seasonRatings: [
      { season: 1, rating: 8.0 },
      { season: 2, rating: 8.5 },
    ],
    dateWatched: "2026-09-27",
  },
  {
    id: "sr9",
    userId: "u1",
    show: shows[8],
    overallRating: 8.6,
    seasonRatings: [
      { season: 1, rating: 8.6 },
      { season: 2, rating: 9.0 },
      { season: 3, rating: 8.0 },
      { season: 4, rating: 8.0 },
    ],
    dateWatched: "2025-02-05",
  },
];
const now = new Date();
const hoursAgo = (h: number) =>
  new Date(now.getTime() - h * 3_600_000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 86_400_000).toISOString();
const daysFromNow = (d: number) =>
  new Date(now.getTime() + d * 86_400_000).toISOString();
export const feedActivities: FeedActivity[] = [
  {
    id: "fa1",
    user: friends[0],
    type: "show_rating",
    show: shows[10],
    season: 3,
    rating: 9.1,
    review: "Parker Posey carried this season on her back.",
    timestamp: hoursAgo(2),
    reactions: { "🔥": ["u1", "u3"], "❤️": ["u4"], "👏": ["u5"] },
    comments: [
      {
        id: "c1",
        userId: "u3",
        user: friends[1],
        text: "Best season of the show",
        timestamp: hoursAgo(1),
      },
    ],
  },
  {
    id: "fa2",
    user: friends[2],
    type: "show_rating",
    show: shows[1],
    season: 1,
    rating: 9.5,
    timestamp: hoursAgo(5),
    reactions: { "❤️": ["u2", "u1"], "😭": ["u5"] },
    comments: [
      {
        id: "c2",
        userId: "u2",
        user: friends[0],
        text: "Jeremy Allen White was incredible",
        timestamp: hoursAgo(3),
      },
      {
        id: "c3",
        userId: "u5",
        user: friends[3],
        text: "Need to rewatch this asap",
        timestamp: hoursAgo(2),
      },
    ],
  },
  {
    id: "fa3",
    user: friends[1],
    type: "watchlist_add",
    show: shows[14],
    timestamp: hoursAgo(8),
    reactions: { "👍": ["u1"] },
  },
  {
    id: "fa4",
    user: friends[3],
    type: "show_rating",
    show: shows[6],
    season: 1,
    rating: 9.0,
    review: "The first episode is one of the best openings in TV.",
    timestamp: hoursAgo(14),
    reactions: { "🔥": ["u2", "u3", "u4"] },
  },
  {
    id: "fa5",
    user: friends[1],
    type: "show_rating",
    show: shows[11],
    rating: 9.3,
    seasonRatings: [
      { season: 1, rating: 9.5 },
      { season: 2, rating: 9.1 },
    ],
    review: "Best Star Wars content since the OT.",
    timestamp: hoursAgo(22),
    reactions: { "🔥": ["u1", "u5"], "❤️": ["u4"] },
  },
  {
    id: "fa6",
    user: friends[0],
    type: "show_rating",
    show: shows[5],
    season: 3,
    rating: 7.2,
    review: "Liked it but didn't love it. Too long between seasons.",
    timestamp: hoursAgo(36),
    reactions: { "😂": ["u3"] },
  },
  {
    id: "fa7",
    user: friends[1],
    type: "show_rating",
    show: shows[1],
    rating: 8.5,
    seasonRatings: [{ season: 3, rating: 8.5 }],
    timestamp: hoursAgo(48),
    reactions: { "👏": ["u1", "u2"] },
  },
  {
    id: "fa8",
    user: friends[3],
    type: "watchlist_add",
    show: shows[13],
    timestamp: hoursAgo(60),
    reactions: {},
  },
  {
    id: "fa9",
    user: friends[2],
    type: "rec_request",
    recQuery:
      "Something like Succession but darker and more cynical — totally hooked on that genre",
    recGenres: ["Drama", "Thriller"],
    timestamp: hoursAgo(3),
    reactions: { "❤️": ["u1"], "👍": ["u3"] },
    comments: [
      {
        id: "c4",
        userId: "u5",
        user: friends[3],
        text: "Miniseries: The Regime. Or try Borgen on Netflix",
        timestamp: hoursAgo(1),
      },
    ],
  },
  {
    id: "fa10",
    user: friends[0],
    type: "rec_request",
    recQuery: "Best horror shows from the last 5 years — go!",
    recGenres: ["Horror"],
    timestamp: hoursAgo(20),
    reactions: { "🔥": ["u3", "u5"] },
    comments: [
      {
        id: "c5",
        userId: "u5",
        user: friends[3],
        text: "Hereditary, no contest",
        timestamp: hoursAgo(18),
      },
      {
        id: "c6",
        userId: "u3",
        user: friends[1],
        text: "Talk to Me was insane",
        timestamp: hoursAgo(16),
      },
    ],
  },
];
export const communityShows: CommunityItem[] = [
  {
    show: shows[0],
    averageRating: 9.7,
    ratingCount: 2210,
    rank: 1,
    pct9plus: 94,
  },
  {
    show: shows[6],
    averageRating: 9.5,
    ratingCount: 1654,
    rank: 2,
    pct9plus: 90,
  },
  {
    show: shows[2],
    averageRating: 9.4,
    ratingCount: 1987,
    rank: 3,
    pct9plus: 87,
  },
  {
    show: shows[3],
    averageRating: 9.2,
    ratingCount: 1102,
    rank: 4,
    pct9plus: 85,
  },
  {
    show: shows[1],
    averageRating: 9.1,
    ratingCount: 1321,
    rank: 5,
    pct9plus: 82,
  },
  {
    show: shows[9],
    averageRating: 9.0,
    ratingCount: 1103,
    rank: 6,
    pct9plus: 81,
  },
  {
    show: shows[7],
    averageRating: 8.9,
    ratingCount: 875,
    rank: 7,
    pct9plus: 79,
  },
  {
    show: shows[4],
    averageRating: 8.8,
    ratingCount: 1441,
    rank: 8,
    pct9plus: 80,
  },
  {
    show: shows[11],
    averageRating: 8.7,
    ratingCount: 987,
    rank: 9,
    pct9plus: 78,
  },
  {
    show: shows[8],
    averageRating: 8.5,
    ratingCount: 765,
    rank: 10,
    pct9plus: 74,
  },
];
export const communitySeasons: CommunityItem[] = [
  { show: shows[0], season: 5, averageRating: 9.9, ratingCount: 1987, rank: 1 },
  { show: shows[2], season: 4, averageRating: 9.8, ratingCount: 1821, rank: 2 },
  { show: shows[6], season: 1, averageRating: 9.7, ratingCount: 1654, rank: 3 },
  { show: shows[0], season: 4, averageRating: 9.6, ratingCount: 1790, rank: 4 },
  { show: shows[1], season: 1, averageRating: 9.5, ratingCount: 1321, rank: 5 },
  { show: shows[3], season: 2, averageRating: 9.4, ratingCount: 1102, rank: 6 },
  { show: shows[11], season: 1, averageRating: 9.4, ratingCount: 987, rank: 7 },
  { show: shows[1], season: 2, averageRating: 9.2, ratingCount: 1201, rank: 8 },
  { show: shows[7], season: 3, averageRating: 9.1, ratingCount: 875, rank: 9 },
  {
    show: shows[4],
    season: 1,
    averageRating: 9.0,
    ratingCount: 1441,
    rank: 10,
  },
];
export const searchableShows: Show[] = [...shows];
export const genres: string[] = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "History",
  "Horror",
  "Music",
  "Musical",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "War",
];
export const tasteMatchPercentages: Record<string, number> = {
  u2: 87,
  u3: 74,
  u4: 62,
  u5: 79,
  u6: 81,
};
const wlNow = new Date();
export const initialWatchlist: WatchlistItem[] = [
  {
    id: "wl1",
    contentType: "show",
    show: shows[14],
    addedDate: new Date(wlNow.getTime() - 86400000 * 2).toISOString(),
    recommendedBy: "friends",
  },
  {
    id: "wl2",
    contentType: "show",
    show: shows[12],
    addedDate: new Date(wlNow.getTime() - 86400000 * 5).toISOString(),
    recommendedBy: "taste",
  },
  {
    id: "wl3",
    contentType: "show",
    show: shows[13],
    addedDate: new Date(wlNow.getTime() - 86400000 * 9).toISOString(),
    recommendedBy: "community",
  },
];
export const friendsShowRatings: Record<
  string,
  { userId: string; rating: number; review?: string }[]
> = {
  s1: [
    {
      userId: "u3",
      rating: 9.9,
      review: "The greatest TV show ever made. Not up for debate.",
    },
  ],
  s2: [
    { userId: "u4", rating: 8.7 },
    { userId: "u2", rating: 9.0, review: "S1 is perfect television." },
  ],
  s3: [
    { userId: "u2", rating: 9.5, review: "The finale destroyed me." },
    { userId: "u3", rating: 8.9 },
  ],
  s12: [
    {
      userId: "u3",
      rating: 9.3,
      review: "Best Star Wars content since the original trilogy.",
    },
  ],
};
export const initialNotifications: Notification[] = [
  {
    id: "n_req_michael",
    type: "rec_request",
    fromUserId: "u6",
    fromUser: friends[4],
    requestId: "rq_michael",
    message: "is looking for a new show to watch",
    timestamp: hoursAgo(2),
    seen: false,
  },
  {
    id: "n_return_slowhorses",
    type: "return_date",
    show: shows[14],
    season: 5,
    message: "Season 5 premiere date announced",
    timestamp: hoursAgo(9),
    seen: false,
  },
  {
    id: "n_started_sofia",
    type: "started_watching",
    fromUserId: "u4",
    fromUser: friends[2],
    show: shows[1],
    season: 3,
    message: "started watching",
    timestamp: hoursAgo(6),
    seen: true,
  },
  {
    id: "n1",
    type: "recommendation",
    fromUserId: "u2",
    fromUser: friends[0],
    show: shows[3],
    message: "You need to watch this NOW, trust me",
    timestamp: hoursAgo(3),
    seen: false,
  },
  {
    id: "n2",
    type: "recommendation",
    fromUserId: "u5",
    fromUser: friends[3],
    show: shows[9],
    message: "This is exactly your vibe",
    timestamp: hoursAgo(18),
    seen: false,
  },
];
